// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTags():Promise<Array<main.Tag>>;

export function GetTasks():Promise<Array<main.Task>>;

export function SaveTag(arg1:string,arg2:string):Promise<main.Tag>;

export function SaveTask(arg1:main.Task):Promise<main.Task>;
