// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function SaveTag(arg1, arg2) {
  return window['go']['main']['App']['SaveTag'](arg1, arg2);
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}
